Int object not iterable? (Python) (URGENT, NEEDED BY TONIGHT) - OpenCV Q&A Forum
First time here? Check out the FAQ!
Hi there! Please sign in help
faq tags users badges
This forum is disabled, please visit https://forum.opencv.org
ALL UNANSWERED
Ask Your Question
-3
Int object not iterable? (Python) (URGENT, NEEDED BY TONIGHT)
edit
3.1.0opencv
EigenFace
eigenfaces
asked
2017-12-13 18:55:40 -0500
nastyheatnor
1
This is really urgent and I need this tomorrow, I cant seem to find a solution anywhere, I have a script that runs a facial recognition script, but for some reason its telling me this exact error:
File "box.py",line 98, in <module>
label,confidence = model.predict(crop)
TypeError: 'int' object is not iterable My code thats actually important to the problem: import cv2 -Creates model to be the facerecognizer
model = cv2.face.createEigenFaceRecognizer() -Defines the model as a training image taken previously
model.load(config.TRAINING_FILE) -Initializes the camera as camera
camera = config.get_camera() -Takes a picture using the camera
image = camera.read() -Converts to grayscale
image = cv2.cvtColor(image, cv2.COLOR_RGB2GRAY) -Results if it found a face
result = face.detect_single(image) -Tells you to keep taking a picture until you have a face recognized if result is None:
print 'Could not see face! Retake picture!'
continue -gets dimensions of the face
x,y,w,h = result -resizes the face
crop = face.resize(face.crop(image, x, y, w, h)) #Tests face against the previously taken model
label, confidence = model.predict(crop) <--- This is where the error is -Im not 100% as to what this does, I got this part on the internet
result = cv2.face.MinDistancePredictCollector()
model.predict(crop)
label = result.getLabel()
confidence = result.getDist() Sorry about the weird formatting, the
thing was being dumb and I couldnt fix it, anyways Thats basically it (Theres obviously some more code set up inside and between but it isnt important or relevant to the issue, at least I dont think, I need this urgently so please somebody respond quick, Im using Python 2.7 with opencv 3.1.0 on a raspbian raspberry pi 3 if you need that information
edit retag
flag offensive
close merge delete
CommentsSorry, we are not doing some code fixing service here! Please read this http://answers.opencv.org/faq/Balaji R (
2017-12-13 21:27:12 -0500
)editthere was a (short lived) bug in 3.1, where you only could use label = model.predict(crop)either update to latest 3.3, or use the MinDistancePredictCollectorberak (
2017-12-14 01:46:33 -0500
)editadd a comment
Links
Official site
GitHub
Wiki
Documentation
Question Tools
Follow
1 follower
subscribe to rss feed
Stats
Asked:
2017-12-13 18:55:40 -0500
Seen: 660 times
Last updated: Dec 13 '17
Related questions
OpenCV compile Eigenface.cpp in Linux with using CodeBlocks
Application cannot distinguish between people [closed]
FaceRecognizer - using multiple models
Online Learning and Confidence with cv::FaceRecognizer
RGB2Gray::operator() causing segmentation fault when using Python
Making FaceRecognizer more accurate [closed]
Eigenfaces face recognizer gives error: unresolved external symbols
facerec_demo model->predict exception thrown
how to get the projections of the training data.
face recognition and face detection using Eigenface
Copyright OpenCV foundation, 2012-2018. Content on this site is licensed under a Creative Commons Attribution Share Alike 3.0 license.
about | faq | help
| privacy policy | terms of service
Powered by Askbot version 0.10.2
Please note: OpenCV answers requires javascript to work properly, please enable javascript in your browser, here is how
(
2021-06-09 17:08:14 -0500
)editnone×