Chapter 4: update Python 2 example for module file location ¬∑ Issue #229 ¬∑ nltk/nltk_book ¬∑ GitHub
Skip to content
Sign¬†up
Why GitHub?
Features ‚Üí
Mobile ‚Üí
Actions ‚Üí
Codespaces ‚Üí
Packages ‚Üí
Security ‚Üí
Code review ‚Üí
Project management ‚Üí
Integrations ‚Üí
GitHub Sponsors ‚Üí
Customer stories‚Üí
Team
Enterprise
Explore
Explore GitHub ‚Üí
Learn and contribute
Topics ‚Üí
Collections ‚Üí
Trending ‚Üí
Learning Lab ‚Üí
Open source guides ‚Üí
Connect with others
The ReadME Project ‚Üí
Events ‚Üí
Community forum ‚Üí
GitHub Education ‚Üí
GitHub Stars program ‚Üí
Marketplace
Pricing
Plans ‚Üí
Compare plans ‚Üí
Contact Sales ‚Üí
Education ‚Üí
In this repository
All GitHub
‚Üµ
Jump to
‚Üµ
No suggested jump to results
In this repository
All GitHub
‚Üµ
Jump to
‚Üµ
In this organization
All GitHub
‚Üµ
Jump to
‚Üµ
In this repository
All GitHub
‚Üµ
Jump to
‚Üµ
Sign in
Sign up
{{ message }}
nltk
/
nltk_book
Notifications
Star
364
Fork
137
Code
Issues
134
Pull requests
11
Actions
Projects
0
Wiki
Security
Insights
More
Code
Issues
Pull requests
Actions
Projects
Wiki
Security
Insights
New issue
Have a question about this project? Sign up for a free GitHub account to open an issue and contact its maintainers and the community.
Pick a username
Email Address
Password
Sign up for GitHub
By clicking ‚ÄúSign up for GitHub‚Äù, you agree to our terms of service and
privacy statement. We‚Äôll occasionally send you account related emails.
Already on GitHub?
Sign in
to your account
Jump to bottom
Chapter 4: update Python 2 example for module file location
#229
Open
pjhinton
opened this issue
Sep 10, 2019
¬∑ 0 comments
Open
Chapter 4: update Python 2 example for module file location
#229
pjhinton
opened this issue
Sep 10, 2019
¬∑ 0 comments
Comments
Copy link
pjhinton
commented
Sep 10, 2019
In section 4.6, there is the following example:
>>> nltk.metrics.distance.__file__
'/usr/lib/python2.5/site-packages/nltk/metrics/distance.pyc'
This fails with Python 3.7.4.
>>> nltk.metrics.distance.__file__
Traceback (most recent call last):
File "<stdin>", line 1, in <module>
NameError: name 'nltk' is not defined
Attempts to import and then expose fail as well:
>>> import nltk.metrics.distance
>>> nltk.metrics.distance.__file__
Traceback (most recent call last):
File "<stdin>", line 1, in <module>
AttributeError: module 'nltk.translate.metrics' has no attribute 'distance'
This code does produce a result:
>>> from nltk.metrics import distance
>>> distance.__file__
'/home/pj/.pyenv/versions/nltkbook/lib/python3.7/site-packages/nltk/metrics/distance.py'
>>> quit()
The reason for this behavior may be a side effect of this import in nltk/__init__.py
from nltk.translate import *
which brings nltk.translate.metrics in as nltk.metrics.
>>> import nltk
>>> nltk.metrics
<module 'nltk.translate.metrics' from '/home/pj/.pyenv/versions/nltkbook/lib/python3.7/site-packages/nltk/translate/metrics.py'>
>>> nltk.metrics.__file__
'/home/pj/.pyenv/versions/nltkbook/lib/python3.7/site-packages/nltk/translate/metrics.py'
The text was updated successfully, but these errors were encountered:
üëç
1
Sign up for free
to join this conversation on GitHub.
Already have an account?
Sign in to comment
Assignees
No one assigned
Labels
None yet
Projects
None yet
Milestone
No milestone
Linked pull requests
Successfully merging a pull request may close this issue.
None yet
1 participant
¬© 2021 GitHub, Inc.
Terms
Privacy
Security
Status
Docs
Contact GitHub
Pricing
API
Training
Blog
About
You can‚Äôt perform that action at this time.
You signed in with another tab or window. Reload to refresh your session.
You signed out in another tab or window. Reload to refresh your session.